# Generated by Django 5.2.5 on 2025-09-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('lead', 'Лид'), ('negotiation', 'Переговоры'), ('signed', 'Подписан'), ('closed', 'Закрыт'), ('canceled', 'Отменён')], default='lead', max_length=20)),
                ('client_name', models.CharField(max_length=255)),
                ('client_phone', models.CharField(max_length=50)),
                ('price_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
