@host = http://127.0.0.1:8000
@api = {{host}}/api/v1/auth
@email = murem810@gmail.com   # ← поставь свою, если отправляешь через SMTP
@name = Emir
@password = 12345678

### 1) Запросить код (на почту придёт письмо)
POST {{api}}/register-request-code/
Content-Type: application/json

{
  "name": "{{name}}",
  "email": "{{email}}",
  "password": "{{password}}"
}

> {% client.test("request code ok", function () {
    client.assert(response.status === 200);
    client.log("Код отправлен на {{email}}");
}) %}

### 2) Подтвердить код (вставь код из письма)
POST {{api}}/register-verify-code/
Content-Type: application/json

{
  "email": "{{email}}",
  "code": "123456"   // ← сюда код из письма
}

> {% client.test("verify ok", function () {
    client.assert(response.status === 200);
    client.assert(response.body.access, "нет access токена");
    client.global.set("accessToken", response.body.access);
}) %}

### 3) Проверка защищёнки (пример)
GET {{host}}/api/v1/properties/
Authorization: Bearer {{accessToken}}

> {% client.test("protected not 401", function () {
    client.assert(response.status !== 401, "Unauthorized");
}) %}
