# Generated by Django 5.2.5 on 2025-09-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='communications',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='condition',
            field=models.CharField(blank=True, choices=[('new_psd', 'Новостройка/ПСД'), ('requires_repair', 'Требует ремонта'), ('cosmetic', 'Косметический'), ('euro', 'Евроремонт')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='cross_streets',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='documents',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='furniture',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='kind',
            field=models.CharField(blank=True, choices=[('elite', 'Элитка'), ('secondary', 'Вторичная'), ('commercial', 'Коммерческая'), ('house_land', 'Дом/участок'), ('club_house', 'Клубный дом'), ('parking', 'Парковка')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='offer_category',
            field=models.CharField(blank=True, choices=[('buyout', 'Выкуп'), ('urgent', 'Срочно'), ('exclusive', 'Эксклюзив')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='offer_type',
            field=models.CharField(blank=True, choices=[('owner', 'Собственник'), ('intermediary', 'Посредник'), ('contractor', 'Подрядчик'), ('realtor', 'Риелтор')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
