# Generated by Django 5.2.5 on 2025-09-03 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_phone', models.CharField(max_length=50)),
                ('starts_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('done', 'Проведен'), ('canceled', 'Отменен')], default='planned', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showings', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showings', to='properties.property')),
            ],
            options={
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['agent', 'starts_at'], name='showings_sh_agent_i_9a2be8_idx')],
            },
        ),
    ]
