# Generated by Django 5.2.5 on 2025-08-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='passwordresetcode',
            index=models.Index(fields=['user', '-created_at'], name='users_passw_user_id_cc0237_idx'),
        ),
    ]
