# Generated by Django 5.2.5 on 2025-09-06 04:47

import core.storages
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_front', models.FileField(blank=True, null=True, storage=core.storages.PrivateMediaStorage(), upload_to='kyc/docs/')),
                ('doc_back', models.FileField(blank=True, null=True, storage=core.storages.PrivateMediaStorage(), upload_to='kyc/docs/')),
                ('selfie', models.FileField(blank=True, null=True, storage=core.storages.PrivateMediaStorage(), upload_to='kyc/selfies/')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Подтверждён'), ('rejected', 'Отклонён')], default='pending', max_length=16)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
