# Generated by Django 5.2.5 on 2025-08-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emaillogincode_registrationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='password_hash',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
