# Generated by Django 5.2.5 on 2025-08-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresetcode_password_hash'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='passwordresetcode',
            name='users_passw_user_id_2b3c18_idx',
        ),
    ]
